### PR TITLE
Empty opts

### PR DESCRIPTION
**Pull request by chuprik**
If you pass an empty array or an object as a parameter, an error will occur.

### CODE REVIEW

**Comment by chuprik** [comment]
I'm sorry, just a few commits. I was looking for a perfect solution.

**Comment by shaneriley** [comment]
Why would you ever pass an array as the options argument? You wouldn't have key/value pairs to tell the plugin what values/methods you're overriding in that instance.

**Comment by chuprik** [comment]
I used array as the argument for dynamic [configure](https://github.com/kotchuprik/yii-localstorage-activeform/blob/master/LSActiveForm.php#L36) component.

**Comment by shaneriley** [comment]
I'm still not understanding why you'd do this. What you've added triggers the constructor, which then extends the opts array on to the defaults object and plugin object. Nothing in that array would correspond to properties or methods on either the defaults object or plugin object. So the end result is effectively a rememberState call with no options, since the resulting plugin object is the default plus a series of properties with values from 0-n, where n is the length of the array you passed in.

**Pull request closed without merging**
